// <auto-generated />
using EnergiaRuralApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EnergiaRuralApi.Migrations
{
    [DbContext(typeof(EnergiaRuralContext))]
    partial class EnergiaRuralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergiaRuralApi.Entities.Simulacao", b =>
                {
                    b.Property<int>("SimulacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SimulacaoId"));

                    b.Property<double>("AreaDisponivel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("ConsumoMedio")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("HorasInsolacao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("RetornoFinanceiro")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("SimulacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("EnergiaRuralApi.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EnergiaRuralApi.Entities.Simulacao", b =>
                {
                    b.HasOne("EnergiaRuralApi.Entities.Usuario", "Usuario")
                        .WithMany("Simulacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnergiaRuralApi.Entities.Usuario", b =>
                {
                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
